### ISSUE TITLE
Spatial-Temporal HAC

### ISSUE THREAD

**Issue by Nosferican** [lbittarello/Microeconometrics.jl#4]
I was looking at the implementation for computing the correlation structure for spatial and temporal HAC. The implementation uses a mapping function for the two dimensional weights into a one dimensional weight as the product of the weights when the inputs are positive. I haven't seen a reference to this method. Usually the spatial-temporal HAC in panel setting is either computed as HAC of averages or averages of HAC (see [Vogelsang 2011](http://dx.doi.org/10.1016/j.jeconom.2011.10.001)). While in my research I test ways to collapse the high dimensional weights to a single correlation structure, the product seems like a bad way of doing it. For example, given some weight in one dimension being a small positive, it might counter a possible high weight by making it very small. A basic, yet better mapping would be to take the maximum. As my research progresses, I would be able suggest a better form. Alternatively, since the estimator is just for spatial-temporal, you could instead implement [Driscoll and Kraay (1998)](https://doi.org/10.1162/003465398557825). Unless I am mistaken in some regard.

**Comment by lbittarello** [comment]
Thanks for the input. The multiplicative form was deliberate. In my own research, observations are correlated across time and space, but this correlation declines along both dimensions. I want a very small weight in one dimension to counter a large weight in another dimension. Unlike Vogelsang (2011) or Driscoll and Kraay (1998), I don't have a panel. I have temporal correlation instead of autocorrelation. Unlike Kelejian and Prucha (2007) or Kim and Sun (2013), I have two independent distance measures instead of two measures of the same distance.

Other users may have different needs. Here are a few proposals:

- We could implement different correlation structures with different names (e.g., `Time and Space 1`, etc.).
- We could allow the user to choose the reduction function: they could ask for weights to be multiplied, for the maximum to be taken, etc.*
- We could remove `Time and space` and implement methods for base operations on correlation structures. Users could then estimate two separate structures and combine them.*

Let me know what you think.

By the way, I'll create a repository for `CorrStructures` and share access. Is the name okay?

\* These strategies may be inefficient if the reduction function is multiplication.

**Comment by Nosferican** [comment]
I like the third option the best for mapping multi-dimensional weights to one dimension. However, as you pointed out, for different applications it might be best to provide the array of options. Therefore, maybe have the default mapping and offer the `Time and Space` for panel settings (your case could be managed with the general reduction function as product of positive weights). For advanced control, users could interact with the list of weight matrices `Vector{Matrix{Float64}}` and create their own mapping `Matrix{Float64}`.

Sounds good. I put in a request for handling the temporal distances with various methods here [#89 ](https://github.com/JuliaStats/Distances.jl/issues/89). If you have any suggestions you can put them there. For the spatial distance, I think we should be fine using Haversine distance from [Distances.jl](https://github.com/JuliaStats/Distances.jl/).

As for the efficiency reduction, assuming the the weights are sparse symmetric, we could take the union of the values positions for each matrix and use intersections reducing the values. Shouldn't be too bad. I imagine the vector would probably be one - three dimensions for the most part.

`CorrStructures` seems like a good name. We can work on those and hold registering it until we decide where to host the ecosystem. Depending on the final product, we might be able to host it in JuliaStats.

**Comment by lbittarello** [comment]
> maybe have the default mapping and offer the Time and Space for panel settings 

Note that `Time and space` isn't meant for panels. It's more general. We should make a distinction between `Time and space` and `SHAC`.

> As for the efficiency reduction, assuming the the weights are sparse symmetric, we could take the union of the values positions for each matrix and use intersections reducing the values

The efficiency gains in the current implementation come from two sources: 1) if the temporal weight is null, you don't need to compute the spatial weight (which is expensive); 2) if either weight is null, you don't need to allocate space in the sparse correlation matrix (which is expensive). We'll lose both.

We can keep `Time and space` *and* implement methods for base operations. That'll be both efficient and flexible.

**Comment by Nosferican** [comment]
For arbitrary multi-dimensional weights you would have to compute k m (m + 1) / 2 (where k is the number of dimensions and m the number of observations). These can be efficiency compute with the Distances package. Afterwards, the kernel has to be trained and then map it for each element. The sparse element would be after computing the distances and mapping the elements. R would then be the reduction of all the others weight matrices. At least that’s what I would think. Lazy computation of the weights only when both are positive requires stronger assumptions, no? I have no issue with specialized methods.
